### ISSUE TITLE
Clarify conventions needed to use sydtest-discover

### ISSUE THREAD

**Issue by ornamentist** [NorfairKing/sydtest#13]
Could I summarize and clarify the file names and conventions needed to use `sydtest-discover`?

With this stack setup:

```
  foobar-test:
    main: Spec.hs
    source-dirs: test/
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sydtest
```

I need to add this line to `test/Spec.hs`:

```
{-# OPTIONS_GHC -F -pgmF sydtest-discover #-}
```

Then when I run `stack test` (or in my case `cabal test`) `sydtest-discover` will find source files in the `test` directory tree matching `*Spec.hs` and include them in the test run?

if I need a custom test `main`, then I need to add to each test file in `test/**.hs` the line:

```
{-# OPTIONS_GHC -F -pgmF sydtest-discover -optF --no-main #-}
```

And also change `main: Spec.hs` in the stack/cabal settings to say `Main.hs`. In that file I can do

```
module Main where

import Spec
import Test.Syd

main :: IO ()
main = sydTest spec
```

Where `Spec.hs` is a file in the `test` directory. If I need multiple test files in the `test` directory then I need to combine their top-level exported `spec` values in the `Main` module in some way?

And many also thanks for creating a such a comprehensive testing framework!
